### ISSUE TITLE
fpm support

### ISSUE THREAD

**Issue by epagone** [scivision/fortran-pathlib#1] opened 2022-01-04 13:03 UTC
Thank you very much for making this very useful library available!

Would it be possible to make it an [fpm](https://github.com/fortran-lang/fpm) package?

**Comment by scivision** [comment] 2022-01-06 04:42
I think the issue is that because I use different source files depending on the compiler and operating system, that that is something that FPM might not be able to do right now.
I don't think this is something that's impossible or difficult for FPM to do. I suppose the question is what syntax to use in the FPM.toml file (feature addition to FPM(.

**Comment by scivision** [comment] 2022-01-06 04:55
I think it was you that suggested on Discourse to use preprocessor statements. I just tried that locally by renaming gcc.F90 and intel.F90 and then in each enclosing the entire file's code by `#ifdef __GFORTRAN__` or `#ifdef __INTEL_COMPILER` but fpm complains like

```
<ERROR>*cmd_build*:target error:Unable to find source for module dependency: "ifport" used by ".\src\intel.F90"
STOP 1
```
when using GCC, hence fpm is ignoring preprocessor statements.

**Comment by scivision** [comment] 2022-01-06 05:07
I made a Discourse post on this https://fortran-lang.discourse.group/t/fpm-if-statements-or-preprocessing/2520

**Comment by scivision** [comment] 2022-01-06 07:23
The latest commit works with `fpm build`

**Comment by scivision** [comment] 2022-01-06 08:11
There might a race condition. Sometimes I have to `fpm build`  a second time on Windows with gfortran

**Comment by epagone** [comment] 2022-01-06 11:13
Many thanks for your time and effort on this issue, very appreciated! I was about to suggest to consider using environmental variables (that is maybe what you were doing already) but I see that you've got a far better suggestion on Discourse.

**Comment by scivision** [comment] 2022-01-14 17:47
I'm moving this to a Project as the logic has become too complex for in-code preprocessor statements, due to increasing use of C standard library

**Closed by scivision** 2022-01-14 17:47 UTC
Labels: enhancement
